### ISSUE TITLE
digest algorithm performance is too low

### ISSUE THREAD

**Issue by yekai123123** [Linaro/openssl-uadk#19]
Uadk's digest algorithm performance is too low compared with NO-SVA mode. 
openssl speed -engine uadk -evp sha256 --async_jobs 1 or openssl speed -engine uadk -evp sha256
result:
type            256 bytes   1024 bytes   2048 bytes   4096 bytes   8192 bytes  16384 bytes  24576 bytes
sha256              98.98k      395.61k      793.86k     1586.34k     3156.65k     6291.46k     9435.87k

no-sva mode:
type            256 bytes   1024 bytes   2048 bytes   4096 bytes   8192 bytes  16384 bytes  24576 bytes  
sha256          307421.24k   230503.08k   351163.73k   462488.92k   608301.21k   716800.00k   769467.16k 
if execute the cipher algorithm.
openssl speed -engine uadk -evp aes-128-cbc --async_jobs 1
type            256 bytes   1024 bytes   2048 bytes   4096 bytes   8192 bytes  16384 bytes  24576 bytes
aes-128-cbc      38167.68k   164071.37k   308686.39k   553049.20k   767635.91k   990325.14k  1064557.49k

 But the hardware level of the two algorithms is similar.

**Comment by gaozhangfei** [comment]
Digest: kae does not support sha256, only support sm3, md5.
So it is software openssl performance.

**Comment by gaozhangfei** [comment]
https://github.com/Linaro/openssl-uadk/pull/40

**Comment by gaozhangfei** [comment]
https://github.com/Linaro/openssl-uadk/pull/40

    digest: malloc data buffer for better performance
    
    Updated data
    type    16 bytes  64 bytes   256 bytes  1024 bytes  8192 bytes  16384 bytes
    sha256  6716.55k  26027.20k  95957.67k  291525.97k  720701.47k  802794.15k
    sha512  6584.85k  26270.95k  97080.75k  319721.81k  965209.39k  1123931.48k
    sm3     6663.45k  25851.43k  95255.72k  290378.07k  718723.34k  801554.43k
    
    vs.
    sha256  6255.52   24.98k     100.27k    400.38k     3192.15k    6373.38k
    sha512  6276.51   25.00k     100.10k    400.04k     3197.61k    6378.84k
    sm3     6250.17   24.96k     100.01k    400.73k     3192.15k    6367.91k
