### ISSUE TITLE
why digest use a cipher function

### ISSUE THREAD

**Issue by lin755** [Linaro/openssl-uadk#47]
In OpenSSL synchronization scenarios, when the MD5 algorithm is run， wd_do_cipher_sync is called in the final stage. The problem can be reproduced if add a printf line to wd_do_cipher_sync function.
CMD: openssl speed -bytes 10000000 -engine uadk -evp md5 --seconds 1

**Comment by gaozhangfei** [comment]
It does not impact performance, and it is called by RAND_bytes
apps/speed.c
if (doit[D_EVP]) { 
// test evp
}
    for (i = 0; i < loopargs_len; i++)
        if (RAND_bytes(loopargs[i].buf, 36) <= 0)   // this called cipher
            goto end;

To verify, can comments this function (two times)

call sequence
speed_main call rand_bytes
RAND_bytes
RAND_DRBG_get0_public
do_rand_drbg_init
drbg_setup
RAND_DRBG_secure_new
rand_drbg_new
RAND_DRBG_set
drbg_ctr_init
uadk_cipher_init nid=426
drbg_ctr_instantiate
uadk_cipher_init nid=426
ctr_update
EVP_CipherUpdate

**Comment by lin755** [comment]
ok, so rand_bytes is use to warming up  memory? I got a description, RAND_bytes() puts num cryptographically strong pseudo-random bytes into buf.

**Comment by gaozhangfei** [comment]
RAND_bytes()  is only used for generating rand numbers
