### ISSUE TITLE
openssl cipher test fail for uadk

### ISSUE THREAD

**Issue by youngersh** [Linaro/openssl-uadk#52]
test:
dd if=/dev/urandom of=data bs=1K count=8
 openssl enc -aes-128-cbc -a -in data -out data.en -pass pass:123456 -K abc -iv abc -engine uadk -p
 openssl enc -aes-128-cbc -a -d -in data.en -out data.de -pass pass:123456 -K abc -iv abc -engine uadk -p

error log():
[root@localhost iter11]# openssl enc -aes-128-cbc -a -in data -out data.en -pass pass:123456 -K abc -iv abc -engine uadk -p
......
[root@localhost iter11]# openssl enc -aes-128-cbc -a -d -in data.en -out data.de -pass pass:123456 -K abc -iv abc -engine uadk -p
......
bad decrypt
281473077186560:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:583:

md5sum data*
137861b7f88c288cc6b3535f876968d4  data
ce5bd7ed86c132734aa2d07b819e922f  data.de
6901aab116a0579b877718690b44746b  data.en

What's more,  the error log are only printed without '-nopad'. But both two mode have a wrong result. And one thing is for sure, the issue occurs in encode.

**Comment by gaozhangfei** [comment]
Test before need -nopad

$ openssl enc -aes-128-cbc -a -d -in data.en -out data.de -pass pass:123456 -K abc -iv abc -engine uadk -p -nopad
engine "uadk" set.
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
hisi sec init Kunpeng920!
hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
salt=85B6DDA2E558306C
key=ABC00000000000000000000000000000
iv =ABC00000000000000000000000000000
hisi sec init Kunpeng920!

**Comment by youngersh** [comment]
Add '-nopad' can only clear the print. But the problem is still exist. And test the openssl software, the encode and decode should add '-nopad' same time.

**Comment by gaozhangfei** [comment]
openssl enc -aes-128-cbc -a -in data -out data.en.1 -pass pass:123456 -K abc -iv abc -engine uadk -p
openssl enc -aes-128-cbc -a -in data -out data.en -pass pass:123456 -K abc -iv abc -p

software enc, no issue
openssl enc -aes-128-cbc -a -d -in data.en -out data.de -pass pass:123456 -K abc -iv abc -engine uadk -p

hardware enc, has issue
openssl enc -aes-128-cbc -a -d -in data.en.1 -out data.de -pass pass:123456 -K abc -iv abc -engine uadk -p

**Comment by gaozhangfei** [comment]
Test can pass with this change

--- a/src/uadk_cipher.c
+++ b/src/uadk_cipher.c
@@ -538,6 +538,13 @@ static int uadk_do_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out,
                        goto out_notify;
        }
 
+       if (priv->setup.mode == WD_CIPHER_CBC) {
+               if (priv->req.op_type == WD_CIPHER_ENCRYPTION) {
+                       out += inlen;
+                       memcpy(priv->iv, out - 16, 16);
+               }
+       }
+
        return 1;

Also KAE will fail if comments this
src/v1/alg/ciphers/sec_ciphers.c
sec_ciphers_update_priv_ctx
        case CBC: 
//*      
                if (priv_ctx->encrypt == OPENSSL_ENCRYPTION) {
                        printf("cbc encrypt\n");
                        kae_memcpy(priv_ctx->iv, priv_ctx->out - 16, 16);  // hardware need 16-byte alignment                  
                }
*/
